[tool.poetry]
name = "ouroboros"
version = "0.1.0"
description = ""
authors = ["Tsvika S <tsvikas@>"]

[tool.poetry.dependencies]
python = "^3.11"
kivy = "~2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
